version: '2.1'

services:

  test:
    build: .
    volumes:
      - .:/usr/src
      #- ../clickhouse-sqlalchemy.git/clickhouse_sqlalchemy:/usr/src/clickhouse_sqlalchemy
    depends_on:
      - ch

  ch:
    image: yandex/clickhouse-server:19
